language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "nightly"

matrix:
    allow_failures:
        - python: nightly
        
install:
  - pip3 install -r requirements.txt
  - pip3 install .[dev]
  - pip3 install --upgrade pytest
script:
  - cd tests
  - pytest --cov-config=.coveragerc --cov=SwaglyricsBot test_bot.py
  - codecov